-- ========================================
-- 0. Extensions
-- ========================================
-- Enable UUID extension (Note: Postgres 13+ supports gen_random_uuid() natively, but keeping this for compatibility)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Enable moddatetime for automatic updated_at timestamps
CREATE EXTENSION IF NOT EXISTS "moddatetime";

-- ========================================
-- 1. Modules
-- ========================================
CREATE TABLE modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    teacher_name TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;

-- Auto-update trigger
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON modules
  FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- ========================================
-- 2. Semesters
-- ========================================
CREATE TABLE semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL, -- e.g. "UCSY 2025/2026 Semester 1"
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_semesters_dates ON semesters (start_date, end_date);

ALTER TABLE semesters ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON semesters
  FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- ========================================
-- 3. Recurring Schedules
-- ========================================
CREATE TABLE recurring_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN recurring_schedules.day_of_week IS '0=Sunday ... 6=Saturday';

CREATE INDEX idx_recurring_schedules_module_semester ON recurring_schedules (module_id, semester_id);

ALTER TABLE recurring_schedules ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON recurring_schedules
  FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- ========================================
-- 4. Class Sessions (Generated Instances)
-- ========================================
CREATE TABLE class_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurring_schedule_id BIGINT NOT NULL REFERENCES recurring_schedules(id) ON DELETE CASCADE,
    module_id BIGINT NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
    semester_id BIGINT NOT NULL REFERENCES semesters(id) ON DELETE CASCADE,
    session_date DATE NOT NULL,
    start_datetime TIMESTAMPTZ NOT NULL,
    end_datetime TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'Not Marked' CHECK (status IN ('Not Marked', 'Present', 'Absent', 'Cancelled', 'Holiday')),
    magic_link_token UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
    google_event_id TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN class_sessions.status IS 'Not Marked, Present, Absent, Cancelled, Holiday';

CREATE INDEX idx_class_sessions_date ON class_sessions (session_date);
CREATE INDEX idx_class_sessions_module_date ON class_sessions (module_id, session_date);
CREATE INDEX idx_class_sessions_semester_date ON class_sessions (semester_id, session_date);
CREATE INDEX idx_class_sessions_status ON class_sessions (status);
CREATE INDEX idx_class_sessions_magic_token ON class_sessions (magic_link_token);

ALTER TABLE class_sessions ENABLE ROW LEVEL SECURITY;

CREATE TRIGGER handle_updated_at BEFORE UPDATE ON class_sessions
  FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- ========================================
-- 5. Holidays (LOOKUP TABLE)
-- ========================================
CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL UNIQUE,
    name TEXT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    -- No updated_at in your original schema, so no trigger needed here
);

CREATE INDEX idx_holidays_date ON holidays (holiday_date);

ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;
